// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	db "github.com/prodsub/pkg/db"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// ProductRepo is an autogenerated mock type for the ProductRepo type
type ProductRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ProductRepo) Create(_a0 *db.Product) (*db.Product, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *db.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(*db.Product) (*db.Product, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*db.Product) *db.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(*db.Product) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ProductRepo) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *ProductRepo) Get(id uuid.UUID) (*db.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *db.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*db.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *db.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: productType
func (_m *ProductRepo) List(productType string) ([]db.Product, error) {
	ret := _m.Called(productType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []db.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.Product, error)); ok {
		return rf(productType)
	}
	if rf, ok := ret.Get(0).(func(string) []db.Product); ok {
		r0 = rf(productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, req
func (_m *ProductRepo) Update(id uuid.UUID, req db.ProductUpdateRequest) (*db.Product, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *db.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, db.ProductUpdateRequest) (*db.Product, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, db.ProductUpdateRequest) *db.Product); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, db.ProductUpdateRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRepo creates a new instance of ProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepo {
	mock := &ProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
